/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sortgame;

import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

/**
 *
 * @author CHAM PC
 */
public class BubbleSort extends javax.swing.JFrame {

    int numberArray[] = new int[5];
    int round = 1, step = 1, count = 0;

    /**
     * Creates new form BubbleSortFiveDigit
     *
     * @param range
     */
    public BubbleSort() {
        initComponents();
        sort1.setVisible(false);
        sort2.setVisible(false);
        sort3.setVisible(false);
        sort4.setVisible(false);
        sort5.setVisible(false);
        sort6.setVisible(false);
        sort7.setVisible(false);
        sort8.setVisible(false);
        sort9.setVisible(false);
        sort10.setVisible(false);
        sort11.setVisible(false);
        sort12.setVisible(false);
        sort13.setVisible(false);
        sort14.setVisible(false);
        sort15.setVisible(false);
        sort16.setVisible(false);
        sort17.setVisible(false);
        sort18.setVisible(false);
        sort19.setVisible(false);
        sort20.setVisible(false);
        sort21.setVisible(false);
        sort22.setVisible(false);
        sort23.setVisible(false);
        sort24.setVisible(false);
        sort25.setVisible(false);

        Random random = new Random();

        int max = 100;
        int min = 1;

        for (int i = 0; i < 5; i++) {
            int randomNumber = random.nextInt(max - min + 1) + min;
            numberArray[i] = randomNumber;
        }

        num1.setText(String.valueOf(numberArray[0]));
        num2.setText(String.valueOf(numberArray[1]));
        num3.setText(String.valueOf(numberArray[2]));
        num4.setText(String.valueOf(numberArray[3]));
        num5.setText(String.valueOf(numberArray[4]));

        this.numDisabling();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        homeBtn = new javax.swing.JButton();
        num1 = new javax.swing.JRadioButton();
        num2 = new javax.swing.JRadioButton();
        num3 = new javax.swing.JRadioButton();
        num4 = new javax.swing.JRadioButton();
        num5 = new javax.swing.JRadioButton();
        sort5 = new javax.swing.JRadioButton();
        sort4 = new javax.swing.JRadioButton();
        sort2 = new javax.swing.JRadioButton();
        sort1 = new javax.swing.JRadioButton();
        sort3 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        sort6 = new javax.swing.JRadioButton();
        sort7 = new javax.swing.JRadioButton();
        sort8 = new javax.swing.JRadioButton();
        sort9 = new javax.swing.JRadioButton();
        sort10 = new javax.swing.JRadioButton();
        sort11 = new javax.swing.JRadioButton();
        sort12 = new javax.swing.JRadioButton();
        sort13 = new javax.swing.JRadioButton();
        sort14 = new javax.swing.JRadioButton();
        sort15 = new javax.swing.JRadioButton();
        sort16 = new javax.swing.JRadioButton();
        sort17 = new javax.swing.JRadioButton();
        sort18 = new javax.swing.JRadioButton();
        sort19 = new javax.swing.JRadioButton();
        sort20 = new javax.swing.JRadioButton();
        sort21 = new javax.swing.JRadioButton();
        sort22 = new javax.swing.JRadioButton();
        sort23 = new javax.swing.JRadioButton();
        sort24 = new javax.swing.JRadioButton();
        sort25 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setText("Learn Bubble Sort");

        homeBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        homeBtn.setText("Home");
        homeBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });

        num1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        num1.setText("1");
        num1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num1ActionPerformed(evt);
            }
        });

        num2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        num2.setText("2");
        num2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num2ActionPerformed(evt);
            }
        });

        num3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        num3.setText("3");
        num3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num3ActionPerformed(evt);
            }
        });

        num4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        num4.setText("4");
        num4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num4ActionPerformed(evt);
            }
        });

        num5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        num5.setText("5");
        num5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num5ActionPerformed(evt);
            }
        });

        sort5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort5.setText("5");
        sort5.setEnabled(false);

        sort4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort4.setText("4");
        sort4.setEnabled(false);

        sort2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort2.setText("2");
        sort2.setEnabled(false);

        sort1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort1.setText("1");
        sort1.setEnabled(false);

        sort3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort3.setText("3");
        sort3.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Select minimum value");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Previous list of numbers");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Exit");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        sort6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort6.setText("1");
        sort6.setEnabled(false);

        sort7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort7.setText("2");
        sort7.setEnabled(false);

        sort8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort8.setText("3");
        sort8.setEnabled(false);

        sort9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort9.setText("4");
        sort9.setEnabled(false);

        sort10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort10.setText("5");
        sort10.setEnabled(false);

        sort11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort11.setText("1");
        sort11.setEnabled(false);

        sort12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort12.setText("2");
        sort12.setEnabled(false);

        sort13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort13.setText("3");
        sort13.setEnabled(false);

        sort14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort14.setText("4");
        sort14.setEnabled(false);

        sort15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort15.setText("5");
        sort15.setEnabled(false);

        sort16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort16.setText("1");
        sort16.setEnabled(false);

        sort17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort17.setText("2");
        sort17.setEnabled(false);

        sort18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort18.setText("3");
        sort18.setEnabled(false);

        sort19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort19.setText("4");
        sort19.setEnabled(false);

        sort20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort20.setText("5");
        sort20.setEnabled(false);

        sort21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort21.setText("1");
        sort21.setEnabled(false);

        sort22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort22.setText("2");
        sort22.setEnabled(false);

        sort23.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort23.setText("3");
        sort23.setEnabled(false);

        sort24.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort24.setText("4");
        sort24.setEnabled(false);

        sort25.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort25.setText("5");
        sort25.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(num1)
                                .addGap(18, 18, 18)
                                .addComponent(num2)
                                .addGap(18, 18, 18)
                                .addComponent(num3)
                                .addGap(18, 18, 18)
                                .addComponent(num4)
                                .addGap(18, 18, 18)
                                .addComponent(num5))
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(sort1)
                                .addGap(18, 18, 18)
                                .addComponent(sort2)
                                .addGap(18, 18, 18)
                                .addComponent(sort3)
                                .addGap(18, 18, 18)
                                .addComponent(sort4)
                                .addGap(18, 18, 18)
                                .addComponent(sort5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(sort6)
                                .addGap(18, 18, 18)
                                .addComponent(sort7)
                                .addGap(18, 18, 18)
                                .addComponent(sort8)
                                .addGap(18, 18, 18)
                                .addComponent(sort9)
                                .addGap(18, 18, 18)
                                .addComponent(sort10))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(sort11)
                                .addGap(18, 18, 18)
                                .addComponent(sort12)
                                .addGap(18, 18, 18)
                                .addComponent(sort13)
                                .addGap(18, 18, 18)
                                .addComponent(sort14)
                                .addGap(18, 18, 18)
                                .addComponent(sort15))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(sort16)
                                .addGap(18, 18, 18)
                                .addComponent(sort17)
                                .addGap(18, 18, 18)
                                .addComponent(sort18)
                                .addGap(18, 18, 18)
                                .addComponent(sort19)
                                .addGap(18, 18, 18)
                                .addComponent(sort20))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(sort21)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(sort22)
                                        .addGap(18, 18, 18)
                                        .addComponent(sort23)
                                        .addGap(18, 18, 18)
                                        .addComponent(sort24)
                                        .addGap(18, 18, 18)
                                        .addComponent(sort25))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(homeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num1)
                    .addComponent(num2)
                    .addComponent(num3)
                    .addComponent(num4)
                    .addComponent(num5))
                .addGap(9, 9, 9)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sort1)
                    .addComponent(sort2)
                    .addComponent(sort3)
                    .addComponent(sort4)
                    .addComponent(sort5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sort6)
                    .addComponent(sort7)
                    .addComponent(sort8)
                    .addComponent(sort9)
                    .addComponent(sort10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sort11)
                    .addComponent(sort12)
                    .addComponent(sort13)
                    .addComponent(sort14)
                    .addComponent(sort15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sort16)
                    .addComponent(sort17)
                    .addComponent(sort18)
                    .addComponent(sort19)
                    .addComponent(sort20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sort21)
                    .addComponent(sort22)
                    .addComponent(sort23)
                    .addComponent(sort24)
                    .addComponent(sort25))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(homeBtn)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        BubbleSortHomeScreen bubbleSortHomeScreen = new BubbleSortHomeScreen();
        bubbleSortHomeScreen.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeBtnActionPerformed

    private void num1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num1ActionPerformed
        if ((round == 1 && step == 4)) {
            this.action(num1, num2);
            num1.setSelected(false);
            round += 1;
            step = 1;
            this.numDisabling();
        }
    }//GEN-LAST:event_num1ActionPerformed

    private void num2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num2ActionPerformed
        if ((round == 1 && step == 3) || (round == 2 && step == 3)) {
            if (round == 2 && step == 3) {
                this.action(num2, num3);
                round += 1;
                step = 1;
                this.numDisabling();
            } else {
                this.action(num2, num3);
            }
            num2.setSelected(false);
            /*if(round == 2 && step == 3){
             round += 1;
             step = 1;
             this.numDisabling();
             }*/
        } else if ((round == 1 && step == 4)) {
            this.action(num1, num2);
            num2.setSelected(false);
            round += 1;
            step = 1;
            this.numDisabling();
        }
    }//GEN-LAST:event_num2ActionPerformed

    private void num3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num3ActionPerformed
        if ((round == 1 && step == 2) || (round == 2 && step == 2) || (round == 3 && step == 2)) {
            if (round == 3 && step == 2) {
                this.action(num3, num4);
                round += 1;
                step = 1;
                this.numDisabling();
            } else {
                this.action(num3, num4);
            }

            num3.setSelected(false);
            /*if(round == 3 && step == 2){
             round += 1;
             step = 1;
             this.numDisabling();
             }*/
        } else if ((round == 1 && step == 3) || (round == 2 && step == 3)) {
            if (round == 2 && step == 3) {
                this.action(num2, num3);
                round += 1;
                step = 1;
                this.numDisabling();
            } else {
                this.action(num2, num3);
            }
            num3.setSelected(false);
            /*if(round == 2 && step == 3){
             round += 1;
             step = 1;
             this.numDisabling();
             }*/
        }
    }//GEN-LAST:event_num3ActionPerformed

    private void num4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num4ActionPerformed
        if ((round == 1 && step == 1) || (round == 2 && step == 1) || (round == 3 && step == 1) || (round == 4 && step == 1)) {
            if (round == 4 && step == 1) {
                this.action(num4, num5);
                round += 1;
                step = 1;
                this.numDisabling();
            } else {
                this.action(num4, num5);
            }

            num4.setSelected(false);
            /*if(round == 4 && step == 1){
             round += 1;
             step = 1;
             this.numDisabling();
             }*/
        } else if ((round == 1 && step == 2) || (round == 2 && step == 2) || (round == 3 && step == 2)) {
            if (round == 3 && step == 2) {
                this.action(num3, num4);
                round += 1;
                step = 1;
                this.numDisabling();
            } else {
                this.action(num3, num4);
            }

            num4.setSelected(false);
            /*if(round == 3 && step == 2){
             round += 1;
             step = 1;
             this.numDisabling();
             }*/
        }
    }//GEN-LAST:event_num4ActionPerformed

    private void num5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num5ActionPerformed
        if ((round == 1 && step == 1) || (round == 2 && step == 1) || (round == 3 && step == 1) || (round == 4 && step == 1)) {
            if (round == 4 && step == 1) {
                this.action(num4, num5);
                round += 1;
                step = 1;
                this.numDisabling();
            } else {
                this.action(num4, num5);
            }

            num5.setSelected(false);
            /*if(round == 4 && step == 1){
             round += 1;
             step = 1;
             this.numDisabling();
             }*/
        }
    }//GEN-LAST:event_num5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    public final void numDisabling() {
        if (round == 1 && step == 1) {
            num1.setEnabled(false);
            num2.setEnabled(false);
            num3.setEnabled(false);
            num4.setEnabled(true);
            num5.setEnabled(true);
        } else if (round == 1 && step == 2) {
            num1.setEnabled(false);
            num2.setEnabled(false);
            num5.setEnabled(false);
            num3.setEnabled(true);
            num4.setEnabled(true);
        } else if (round == 1 && step == 3) {
            num1.setEnabled(false);
            num4.setEnabled(false);
            num5.setEnabled(false);
            num2.setEnabled(true);
            num3.setEnabled(true);
        } else if (round == 1 && step == 4) {
            num3.setEnabled(false);
            num4.setEnabled(false);
            num5.setEnabled(false);
            num1.setEnabled(true);
            num2.setEnabled(true);
        } else if (round == 2 && step == 1) {
            num1.setEnabled(false);
            num2.setEnabled(false);
            num3.setEnabled(false);
            num4.setEnabled(true);
            num5.setEnabled(true);
        } else if (round == 2 && step == 2) {
            num1.setEnabled(false);
            num2.setEnabled(false);
            num5.setEnabled(false);
            num3.setEnabled(true);
            num4.setEnabled(true);
        } else if (round == 2 && step == 3) {
            num1.setEnabled(false);
            num4.setEnabled(false);
            num5.setEnabled(false);
            num2.setEnabled(true);
            num3.setEnabled(true);
        } else if (round == 3 && step == 1) {
            num1.setEnabled(false);
            num2.setEnabled(false);
            num3.setEnabled(false);
            num4.setEnabled(true);
            num5.setEnabled(true);
        } else if (round == 3 && step == 2) {
            num1.setEnabled(false);
            num2.setEnabled(false);
            num5.setEnabled(false);
            num3.setEnabled(true);
            num4.setEnabled(true);
        } else if (round == 4 && step == 1) {
            num1.setEnabled(false);
            num2.setEnabled(false);
            num3.setEnabled(false);
            num4.setEnabled(true);
            num5.setEnabled(true);
        } else if (round == 5) {
            num1.setEnabled(false);
            num2.setEnabled(false);
            num3.setEnabled(false);
            num4.setEnabled(false);
            num5.setEnabled(false);
            JOptionPane.showMessageDialog(this, "You won the game...!");
        }
    }

    public void action(JRadioButton one, JRadioButton two) {
        int numone = Integer.parseInt(one.getText());
        int numtwo = Integer.parseInt(two.getText());
        if (one.isSelected() && (numone <= numtwo)) {
            step += 1;
            //round += 1;
            count = 0;
            this.numDisabling();
        } else if (two.isSelected() && (numtwo <= numone)) {
            two.setText(numone + "");
            one.setText(numtwo + "");
            step += 1;
            //round += 1;
            count = 0;
            this.numDisabling();
        } else {
            if (count < 1) {
                JOptionPane.showMessageDialog(this, "Invalid Selection! \n You have only two chances.");
                num5.setSelected(false);
                count += 1;
            } else if (count < 2) {
                JOptionPane.showMessageDialog(this, "Invalid Selection! \n You have only one chance.");
                num5.setSelected(false);
                count += 1;
            } else {
                JOptionPane.showMessageDialog(this, "You lost the game!");
                BubbleSortHomeScreen BubbleSortHomeScreen = new BubbleSortHomeScreen();
                BubbleSortHomeScreen.setVisible(true);
                this.dispose();
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BubbleSort.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BubbleSort.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BubbleSort.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BubbleSort.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BubbleSort().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton homeBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton num1;
    private javax.swing.JRadioButton num2;
    private javax.swing.JRadioButton num3;
    private javax.swing.JRadioButton num4;
    private javax.swing.JRadioButton num5;
    private javax.swing.JRadioButton sort1;
    private javax.swing.JRadioButton sort10;
    private javax.swing.JRadioButton sort11;
    private javax.swing.JRadioButton sort12;
    private javax.swing.JRadioButton sort13;
    private javax.swing.JRadioButton sort14;
    private javax.swing.JRadioButton sort15;
    private javax.swing.JRadioButton sort16;
    private javax.swing.JRadioButton sort17;
    private javax.swing.JRadioButton sort18;
    private javax.swing.JRadioButton sort19;
    private javax.swing.JRadioButton sort2;
    private javax.swing.JRadioButton sort20;
    private javax.swing.JRadioButton sort21;
    private javax.swing.JRadioButton sort22;
    private javax.swing.JRadioButton sort23;
    private javax.swing.JRadioButton sort24;
    private javax.swing.JRadioButton sort25;
    private javax.swing.JRadioButton sort3;
    private javax.swing.JRadioButton sort4;
    private javax.swing.JRadioButton sort5;
    private javax.swing.JRadioButton sort6;
    private javax.swing.JRadioButton sort7;
    private javax.swing.JRadioButton sort8;
    private javax.swing.JRadioButton sort9;
    // End of variables declaration//GEN-END:variables
}
