/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sortgame;

import static sortgame.SortGame.homeScreen;

/**
 *
 * @author ASHI
 */
public class BubbleSortHomeScreen extends javax.swing.JFrame {

    /**
     * Creates new form BubbleSortHomeScreen
     */
    public BubbleSortHomeScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tDigitsRadioBtn = new javax.swing.JRadioButton();
        fDigitsRadioBtn = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        twoRangeRadioBtn = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        threeRangeRadioBtn = new javax.swing.JRadioButton();
        homeBtn = new javax.swing.JButton();
        startBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tDigitsRadioBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tDigitsRadioBtn.setText("10");
        tDigitsRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tDigitsRadioBtnActionPerformed(evt);
            }
        });

        fDigitsRadioBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        fDigitsRadioBtn.setText("5");
        fDigitsRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fDigitsRadioBtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Select no.of digits to sort");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Select number range");

        twoRangeRadioBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        twoRangeRadioBtn.setText("1 to 10");
        twoRangeRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoRangeRadioBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setText("Learn Bubble Sort");

        threeRangeRadioBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        threeRangeRadioBtn.setText("1 to 100");
        threeRangeRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeRangeRadioBtnActionPerformed(evt);
            }
        });

        homeBtn.setText("Back to Home");
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });

        startBtn.setText("Start");
        startBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(36, 36, 36)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(twoRangeRadioBtn)
                                    .addComponent(fDigitsRadioBtn)))
                            .addComponent(homeBtn, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tDigitsRadioBtn)
                            .addComponent(threeRangeRadioBtn)
                            .addComponent(startBtn, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(0, 24, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fDigitsRadioBtn)
                    .addComponent(tDigitsRadioBtn))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(twoRangeRadioBtn)
                    .addComponent(threeRangeRadioBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startBtn)
                    .addComponent(homeBtn))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tDigitsRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tDigitsRadioBtnActionPerformed
        if (fDigitsRadioBtn.isSelected()){
            fDigitsRadioBtn.setSelected(false);
        }
    }//GEN-LAST:event_tDigitsRadioBtnActionPerformed

    private void fDigitsRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fDigitsRadioBtnActionPerformed
        if (tDigitsRadioBtn.isSelected()){
            tDigitsRadioBtn.setSelected(false);
        }
    }//GEN-LAST:event_fDigitsRadioBtnActionPerformed

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        homeScreen.setVisible(true);
        //HomeScreen homeScreen = new HomeScreen();
        //homeScreen.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeBtnActionPerformed

    private void twoRangeRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoRangeRadioBtnActionPerformed
        if (threeRangeRadioBtn.isSelected()){
            threeRangeRadioBtn.setSelected(false);
        }
    }//GEN-LAST:event_twoRangeRadioBtnActionPerformed

    private void threeRangeRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeRangeRadioBtnActionPerformed
        if (twoRangeRadioBtn.isSelected()){
            twoRangeRadioBtn.setSelected(false);
        }
    }//GEN-LAST:event_threeRangeRadioBtnActionPerformed

    private void startBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startBtnActionPerformed
        if (fDigitsRadioBtn.isSelected()){
            if (twoRangeRadioBtn.isSelected()){
                BubbleSort bubbleSortFiveDigit = new BubbleSort(2);
                bubbleSortFiveDigit.setVisible(true);
            }else if (threeRangeRadioBtn.isSelected()){
                BubbleSort bubbleSortFiveDigit = new BubbleSort(3);
                bubbleSortFiveDigit.setVisible(true);
            }
            this.dispose();
        }else if (tDigitsRadioBtn.isSelected()){
        
        }
    }//GEN-LAST:event_startBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BubbleSortHomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BubbleSortHomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BubbleSortHomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BubbleSortHomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BubbleSortHomeScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton fDigitsRadioBtn;
    private javax.swing.JButton homeBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton startBtn;
    private javax.swing.JRadioButton tDigitsRadioBtn;
    private javax.swing.JRadioButton threeRangeRadioBtn;
    private javax.swing.JRadioButton twoRangeRadioBtn;
    // End of variables declaration//GEN-END:variables
}
