/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package sortgame;

/**
 *
 * @author CHAM PC
 */
public class BubbleSortSub extends javax.swing.JFrame {

    /**
     * Creates new form BubbleSortSub
     */
    public BubbleSortSub() {
        initComponents();
        
        round1Lbl.setVisible(false);
        round2Lbl.setVisible(false);
        round3Lbl.setVisible(false);
        round4Lbl.setVisible(false);
        sort11.setVisible(false);
        sort12.setVisible(false);
        sort13.setVisible(false);
        sort14.setVisible(false);
        sort15.setVisible(false);
        sort21.setVisible(false);
        sort22.setVisible(false);
        sort23.setVisible(false);
        sort24.setVisible(false);
        sort25.setVisible(false);
        sort31.setVisible(false);
        sort32.setVisible(false);
        sort33.setVisible(false);
        sort34.setVisible(false);
        sort35.setVisible(false);
        sort41.setVisible(false);
        sort42.setVisible(false);
        sort43.setVisible(false);
        sort44.setVisible(false);
        sort45.setVisible(false);
        
        num1.setEnabled(false);
        num2.setEnabled(false);
        num3.setEnabled(false);
        num4.setEnabled(false);
        num5.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        num1 = new javax.swing.JRadioButton();
        num2 = new javax.swing.JRadioButton();
        num3 = new javax.swing.JRadioButton();
        num4 = new javax.swing.JRadioButton();
        num5 = new javax.swing.JRadioButton();
        sort15 = new javax.swing.JRadioButton();
        sort14 = new javax.swing.JRadioButton();
        sort12 = new javax.swing.JRadioButton();
        sort11 = new javax.swing.JRadioButton();
        sort13 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        round1Lbl = new javax.swing.JLabel();
        round2Lbl = new javax.swing.JLabel();
        sort21 = new javax.swing.JRadioButton();
        sort22 = new javax.swing.JRadioButton();
        sort23 = new javax.swing.JRadioButton();
        sort24 = new javax.swing.JRadioButton();
        sort25 = new javax.swing.JRadioButton();
        round3Lbl = new javax.swing.JLabel();
        sort31 = new javax.swing.JRadioButton();
        sort32 = new javax.swing.JRadioButton();
        sort33 = new javax.swing.JRadioButton();
        sort34 = new javax.swing.JRadioButton();
        sort35 = new javax.swing.JRadioButton();
        round4Lbl = new javax.swing.JLabel();
        sort41 = new javax.swing.JRadioButton();
        sort42 = new javax.swing.JRadioButton();
        sort43 = new javax.swing.JRadioButton();
        sort44 = new javax.swing.JRadioButton();
        sort45 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));

        jLabel1.setFont(new java.awt.Font("Trajan Pro", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 255));
        jLabel1.setText("Learn Bubble Sort");

        num1.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        num1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        num1.setText("1");
        num1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num1ActionPerformed(evt);
            }
        });

        num2.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        num2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        num2.setText("2");
        num2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num2ActionPerformed(evt);
            }
        });

        num3.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        num3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        num3.setText("3");
        num3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num3ActionPerformed(evt);
            }
        });

        num4.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        num4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        num4.setText("4");
        num4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num4ActionPerformed(evt);
            }
        });

        num5.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        num5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        num5.setText("5");
        num5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num5ActionPerformed(evt);
            }
        });

        sort15.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        sort15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort15.setText("5");
        sort15.setEnabled(false);

        sort14.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        sort14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort14.setText("4");
        sort14.setEnabled(false);

        sort12.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        sort12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort12.setText("2");
        sort12.setEnabled(false);

        sort11.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        sort11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort11.setText("1");
        sort11.setEnabled(false);
        sort11.setHideActionText(true);
        sort11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sort11ActionPerformed(evt);
            }
        });

        sort13.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        sort13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort13.setText("3");
        sort13.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel2.setText("Original Sequence");

        round1Lbl.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        round1Lbl.setText("Round 1");

        round2Lbl.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        round2Lbl.setText("Round 2");

        sort21.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        sort21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort21.setText("1");
        sort21.setEnabled(false);
        sort21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sort21ActionPerformed(evt);
            }
        });

        sort22.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        sort22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort22.setText("2");
        sort22.setEnabled(false);

        sort23.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        sort23.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort23.setText("3");
        sort23.setEnabled(false);

        sort24.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        sort24.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort24.setText("4");
        sort24.setEnabled(false);
        sort24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sort24ActionPerformed(evt);
            }
        });

        sort25.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        sort25.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort25.setText("5");
        sort25.setEnabled(false);

        round3Lbl.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        round3Lbl.setText("Round 3");

        sort31.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        sort31.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort31.setText("1");
        sort31.setEnabled(false);

        sort32.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        sort32.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort32.setText("2");
        sort32.setEnabled(false);

        sort33.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        sort33.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort33.setText("3");
        sort33.setEnabled(false);
        sort33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sort33ActionPerformed(evt);
            }
        });

        sort34.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        sort34.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort34.setText("4");
        sort34.setEnabled(false);

        sort35.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        sort35.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort35.setText("5");
        sort35.setEnabled(false);

        round4Lbl.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        round4Lbl.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        round4Lbl.setText("Round 4");

        sort41.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        sort41.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort41.setText("1");
        sort41.setEnabled(false);

        sort42.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        sort42.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort42.setText("2");
        sort42.setEnabled(false);

        sort43.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        sort43.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort43.setText("3");
        sort43.setEnabled(false);

        sort44.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        sort44.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort44.setText("4");
        sort44.setEnabled(false);

        sort45.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        sort45.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort45.setText("5");
        sort45.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(sort11)
                                .addGap(18, 18, 18)
                                .addComponent(sort12))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(num1)
                                .addGap(18, 18, 18)
                                .addComponent(num2)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(num3)
                                .addGap(18, 18, 18)
                                .addComponent(num4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(sort13)
                                .addGap(18, 18, 18)
                                .addComponent(sort14)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sort15)
                            .addComponent(num5)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(round1Lbl)
                            .addComponent(round2Lbl)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(round3Lbl)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(sort21)
                                        .addGap(18, 18, 18)
                                        .addComponent(sort22)
                                        .addGap(18, 18, 18)
                                        .addComponent(sort23)
                                        .addGap(18, 18, 18)
                                        .addComponent(sort24)))
                                .addGap(18, 18, 18)
                                .addComponent(sort25))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(round4Lbl)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(sort31)
                                        .addGap(18, 18, 18)
                                        .addComponent(sort32)
                                        .addGap(18, 18, 18)
                                        .addComponent(sort33)
                                        .addGap(18, 18, 18)
                                        .addComponent(sort34)))
                                .addGap(18, 18, 18)
                                .addComponent(sort35))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(sort41)
                                .addGap(18, 18, 18)
                                .addComponent(sort42)
                                .addGap(18, 18, 18)
                                .addComponent(sort43)
                                .addGap(18, 18, 18)
                                .addComponent(sort44)
                                .addGap(18, 18, 18)
                                .addComponent(sort45))))
                    .addComponent(jLabel1))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num1)
                    .addComponent(num2)
                    .addComponent(num3)
                    .addComponent(num4)
                    .addComponent(num5))
                .addGap(7, 7, 7)
                .addComponent(round1Lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sort12)
                    .addComponent(sort11)
                    .addComponent(sort13)
                    .addComponent(sort14)
                    .addComponent(sort15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(round2Lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sort21)
                    .addComponent(sort22)
                    .addComponent(sort23)
                    .addComponent(sort24)
                    .addComponent(sort25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(round3Lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sort31)
                    .addComponent(sort32)
                    .addComponent(sort33)
                    .addComponent(sort34)
                    .addComponent(sort35))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(round4Lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sort41)
                    .addComponent(sort42)
                    .addComponent(sort43)
                    .addComponent(sort44)
                    .addComponent(sort45))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void num1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num1ActionPerformed

    }//GEN-LAST:event_num1ActionPerformed

    private void num2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num2ActionPerformed

    }//GEN-LAST:event_num2ActionPerformed

    private void num3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num3ActionPerformed

    }//GEN-LAST:event_num3ActionPerformed

    private void num4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num4ActionPerformed

    }//GEN-LAST:event_num4ActionPerformed

    private void num5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num5ActionPerformed

    }//GEN-LAST:event_num5ActionPerformed

    private void sort11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sort11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sort11ActionPerformed

    private void sort21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sort21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sort21ActionPerformed

    private void sort24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sort24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sort24ActionPerformed

    private void sort33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sort33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sort33ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BubbleSortSub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BubbleSortSub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BubbleSortSub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BubbleSortSub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BubbleSortSub().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    protected javax.swing.JRadioButton num1;
    protected javax.swing.JRadioButton num2;
    protected javax.swing.JRadioButton num3;
    protected javax.swing.JRadioButton num4;
    protected javax.swing.JRadioButton num5;
    protected javax.swing.JLabel round1Lbl;
    protected javax.swing.JLabel round2Lbl;
    protected javax.swing.JLabel round3Lbl;
    protected javax.swing.JLabel round4Lbl;
    protected javax.swing.JRadioButton sort11;
    protected javax.swing.JRadioButton sort12;
    protected javax.swing.JRadioButton sort13;
    protected javax.swing.JRadioButton sort14;
    protected javax.swing.JRadioButton sort15;
    protected javax.swing.JRadioButton sort21;
    protected javax.swing.JRadioButton sort22;
    protected javax.swing.JRadioButton sort23;
    protected javax.swing.JRadioButton sort24;
    protected javax.swing.JRadioButton sort25;
    protected javax.swing.JRadioButton sort31;
    protected javax.swing.JRadioButton sort32;
    protected javax.swing.JRadioButton sort33;
    protected javax.swing.JRadioButton sort34;
    protected javax.swing.JRadioButton sort35;
    protected javax.swing.JRadioButton sort41;
    protected javax.swing.JRadioButton sort42;
    protected javax.swing.JRadioButton sort43;
    protected javax.swing.JRadioButton sort44;
    protected javax.swing.JRadioButton sort45;
    // End of variables declaration//GEN-END:variables
}
