/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sortgame;

import com.sun.jna.Native;
import com.sun.jna.NativeLibrary;
import java.awt.BorderLayout;
import java.awt.Canvas;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JPanel;
import uk.co.caprica.vlcj.binding.LibVlc;
import uk.co.caprica.vlcj.player.MediaPlayerFactory;
import uk.co.caprica.vlcj.player.embedded.EmbeddedMediaPlayer;
import uk.co.caprica.vlcj.runtime.RuntimeUtil;

/**
 *
 * @author ASHI
 */
public class HomeScreen extends javax.swing.JFrame {

    /**
     * Creates new form HomeScreen
     */
    public HomeScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        selectionRadioBtn = new javax.swing.JRadioButton();
        insertionRadioBtn = new javax.swing.JRadioButton();
        bubbleRadioBtn = new javax.swing.JRadioButton();
        okBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Learn Basic Sorting Algorithms");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Select a Sorting Algorithm to proceed");

        selectionRadioBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        selectionRadioBtn.setText("Selection Sort");
        selectionRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectionRadioBtnActionPerformed(evt);
            }
        });

        insertionRadioBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        insertionRadioBtn.setText("Insertion Sort");
        insertionRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertionRadioBtnActionPerformed(evt);
            }
        });

        bubbleRadioBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bubbleRadioBtn.setText("Bubble Sort");
        bubbleRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bubbleRadioBtnActionPerformed(evt);
            }
        });

        okBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        okBtn.setText("Ok");
        okBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        okBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBtnActionPerformed(evt);
            }
        });

        cancelBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cancelBtn.setText("Exit");
        cancelBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addComponent(cancelBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(okBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(selectionRadioBtn)
                                .addGap(18, 18, 18)
                                .addComponent(insertionRadioBtn)))
                        .addGap(18, 18, 18)
                        .addComponent(bubbleRadioBtn)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectionRadioBtn)
                    .addComponent(insertionRadioBtn)
                    .addComponent(bubbleRadioBtn))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okBtn)
                    .addComponent(cancelBtn))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectionRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectionRadioBtnActionPerformed
        if (insertionRadioBtn.isSelected()) {
            insertionRadioBtn.setSelected(false);
        } else if (bubbleRadioBtn.isSelected()) {
            bubbleRadioBtn.setSelected(false);
        }
    }//GEN-LAST:event_selectionRadioBtnActionPerformed

    private void insertionRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertionRadioBtnActionPerformed
        if (selectionRadioBtn.isSelected()) {
            selectionRadioBtn.setSelected(false);
        } else if (bubbleRadioBtn.isSelected()) {
            bubbleRadioBtn.setSelected(false);
        }
    }//GEN-LAST:event_insertionRadioBtnActionPerformed

    private void bubbleRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bubbleRadioBtnActionPerformed
        if (selectionRadioBtn.isSelected()) {
            selectionRadioBtn.setSelected(false);
        } else if (insertionRadioBtn.isSelected()) {
            insertionRadioBtn.setSelected(false);
        }
    }//GEN-LAST:event_bubbleRadioBtnActionPerformed

    private void okBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBtnActionPerformed
        if (selectionRadioBtn.isSelected()) {

            /* Video play start */
            SelectionSortVideo selectionSortVideo = new SelectionSortVideo();
            selectionSortVideo.setLocation(100, 100);
            selectionSortVideo.setSize(600,600);
            selectionSortVideo.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            selectionSortVideo.setVisible(true);

            Canvas canvas = new Canvas();

            canvas.setBackground(Color.black);

            try {
                selectionSortVideo.videoPanel.setLayout(new BorderLayout());

                selectionSortVideo.videoPanel.add(canvas);
                selectionSortVideo.add(selectionSortVideo.videoPanel);

                NativeLibrary.addSearchPath(RuntimeUtil.getLibVlcLibraryName(), "lib");
                Native.loadLibrary(RuntimeUtil.getLibVlcLibraryName(), LibVlc.class);

                MediaPlayerFactory mpf = new MediaPlayerFactory();

                EmbeddedMediaPlayer emp = mpf.newEmbeddedMediaPlayer();
                emp.setVideoSurface(mpf.newVideoSurface(canvas));

                emp.toggleFullScreen();

                emp.setEnableKeyInputHandling(false);
                emp.setEnableMouseInputHandling(false);

                String file = "Selection Sort Intro.mp4";

                emp.prepareMedia(file);

                emp.play();

            } catch (Exception e) {
                System.err.println("Exception : " + e);
            }

            this.setVisible(false);

        } else if (insertionRadioBtn.isSelected()) {
            InsertionSortHomeScreen insertionSortHomeScreen = new InsertionSortHomeScreen();
            insertionSortHomeScreen.setVisible(true);
        } else if (bubbleRadioBtn.isSelected()) {
            BubbleSortHomeScreen bubbleSortHomeScreen = new BubbleSortHomeScreen();
            bubbleSortHomeScreen.setVisible(true);
        }
    }//GEN-LAST:event_okBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_cancelBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton bubbleRadioBtn;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JRadioButton insertionRadioBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton okBtn;
    private javax.swing.JRadioButton selectionRadioBtn;
    // End of variables declaration//GEN-END:variables
}
