/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sortgame;

import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author ASHI
 */
public class SelectionSortFiveDigit extends javax.swing.JFrame {

    int numberArray[] = new int[5];
    int round = 1;

    /**
     * Creates new form SelectionSortFiveDigit
     *
     * @param range
     */
    public SelectionSortFiveDigit(int range) {
        initComponents();

        sort1.setVisible(false);
        sort2.setVisible(false);
        sort3.setVisible(false);
        sort4.setVisible(false);
        sort5.setVisible(false);

        Random random = new Random();

        if (range == 2) {

            int max = 10;
            int min = 1;

            for (int i = 0; i < 5; i++) {
                int randomNumber = random.nextInt(max - min + 1) + min;
                numberArray[i] = randomNumber;
            }
        } else {
            int max = 100;
            int min = 1;

            for (int i = 0; i < 5; i++) {
                int randomNumber = random.nextInt(max - min + 1) + min;
                numberArray[i] = randomNumber;
            }
        }

        num1.setText(String.valueOf(numberArray[0]));
        num2.setText(String.valueOf(numberArray[1]));
        num3.setText(String.valueOf(numberArray[2]));
        num4.setText(String.valueOf(numberArray[3]));
        num5.setText(String.valueOf(numberArray[4]));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        homeBtn = new javax.swing.JButton();
        num1 = new javax.swing.JRadioButton();
        num2 = new javax.swing.JRadioButton();
        num3 = new javax.swing.JRadioButton();
        num4 = new javax.swing.JRadioButton();
        num5 = new javax.swing.JRadioButton();
        sort5 = new javax.swing.JRadioButton();
        sort4 = new javax.swing.JRadioButton();
        sort2 = new javax.swing.JRadioButton();
        sort1 = new javax.swing.JRadioButton();
        sort3 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setText("Learn Selection Sort");

        homeBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        homeBtn.setText("Back to Home");
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });

        num1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        num1.setText("1");
        num1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num1ActionPerformed(evt);
            }
        });

        num2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        num2.setText("2");
        num2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num2ActionPerformed(evt);
            }
        });

        num3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        num3.setText("3");
        num3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num3ActionPerformed(evt);
            }
        });

        num4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        num4.setText("4");
        num4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num4ActionPerformed(evt);
            }
        });

        num5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        num5.setText("5");
        num5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num5ActionPerformed(evt);
            }
        });

        sort5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort5.setText("5");
        sort5.setEnabled(false);

        sort4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort4.setText("4");
        sort4.setEnabled(false);

        sort2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort2.setText("2");
        sort2.setEnabled(false);

        sort1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort1.setText("1");
        sort1.setEnabled(false);

        sort3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort3.setText("3");
        sort3.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Select minimum value");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Previous list of numbers");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(num1)
                                .addGap(18, 18, 18)
                                .addComponent(num2)
                                .addGap(18, 18, 18)
                                .addComponent(num3)
                                .addGap(18, 18, 18)
                                .addComponent(num4)
                                .addGap(18, 18, 18)
                                .addComponent(num5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(sort1)
                                .addGap(18, 18, 18)
                                .addComponent(sort2)
                                .addGap(18, 18, 18)
                                .addComponent(sort3)
                                .addGap(18, 18, 18)
                                .addComponent(sort4)
                                .addGap(18, 18, 18)
                                .addComponent(sort5))
                            .addComponent(jLabel2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(homeBtn)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num1)
                    .addComponent(num2)
                    .addComponent(num3)
                    .addComponent(num4)
                    .addComponent(num5))
                .addGap(9, 9, 9)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sort1)
                    .addComponent(sort2)
                    .addComponent(sort3)
                    .addComponent(sort4)
                    .addComponent(sort5))
                .addGap(18, 18, 18)
                .addComponent(homeBtn)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        SelectionSortHomeScreen selectionSortHomeScreen = new SelectionSortHomeScreen();
        selectionSortHomeScreen.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_homeBtnActionPerformed

    private void num1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num1ActionPerformed
        int selectedValue = Integer.parseInt(num1.getText());
        if (this.checkValue(selectedValue,round-1)) {
            if (round == 1) {
                this.setPreviousValues();
                this.setVisibleOldValues();
                this.setNumberArray();
                num1.setSelected(false);
                num1.setEnabled(false);
                round += 1;
            }
        }
    }//GEN-LAST:event_num1ActionPerformed

    private void num2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num2ActionPerformed
        int selectedValue = Integer.parseInt(num2.getText());
        if (this.checkValue(selectedValue,round-1)) {
            if (round == 1) {
                this.setPreviousValues();
                String x = num1.getText();
                String y = num2.getText();
                num1.setText(y);
                num2.setText(x);
                this.setVisibleOldValues();
                this.setNumberArray();
                num2.setSelected(false);
                num1.setEnabled(false);
                round += 1;
            } else if(round == 2){
                this.setPreviousValues();
                this.setVisibleOldValues();
                this.setNumberArray();
                num2.setSelected(false);
                num2.setEnabled(false);
                round += 1;
            }
        }
    }//GEN-LAST:event_num2ActionPerformed

    private void num3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num3ActionPerformed
        int selectedValue = Integer.parseInt(num3.getText());
        if (this.checkValue(selectedValue,round-1)) {
            if (round == 1) {
                this.setPreviousValues();
                String x = num1.getText();
                String y = num3.getText();
                num1.setText(y);
                num3.setText(x);
                this.setVisibleOldValues();
                this.setNumberArray();
                num3.setSelected(false);
                num1.setEnabled(false);
                round += 1;
            } else if(round == 2){
                this.setPreviousValues();
                String x = num2.getText();
                String y = num3.getText();
                num2.setText(y);
                num3.setText(x);
                this.setVisibleOldValues();
                this.setNumberArray();
                num3.setSelected(false);
                num2.setEnabled(false);
                round += 1;
            } else if(round == 3){
                this.setPreviousValues();
                this.setVisibleOldValues();
                this.setNumberArray();
                num3.setSelected(false);
                num3.setEnabled(false);
                round += 1;
            }
        }
    }//GEN-LAST:event_num3ActionPerformed

    private void num4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num4ActionPerformed
        int selectedValue = Integer.parseInt(num4.getText());
        if (this.checkValue(selectedValue,round-1)) {
            if (round == 1) {
                this.setPreviousValues();
                String x = num1.getText();
                String y = num4.getText();
                num1.setText(y);
                num4.setText(x);
                this.setVisibleOldValues();
                this.setNumberArray();
                num4.setSelected(false);
                num1.setEnabled(false);
                round += 1;
            } else if(round == 2){
                this.setPreviousValues();
                String x = num2.getText();
                String y = num4.getText();
                num2.setText(y);
                num4.setText(x);
                this.setVisibleOldValues();
                this.setNumberArray();
                num4.setSelected(false);
                num2.setEnabled(false);
                round += 1;
            } else if (round == 3){
                this.setPreviousValues();
                String x = num3.getText();
                String y = num4.getText();
                num3.setText(y);
                num4.setText(x);
                this.setVisibleOldValues();
                this.setNumberArray();
                num4.setSelected(false);
                num3.setEnabled(false);
                round += 1;
            } else if (round == 4){
                this.setPreviousValues();
                this.setVisibleOldValues();
                this.setNumberArray();
                num4.setSelected(false);
                num4.setEnabled(false);
                round += 1;
            }
        }
    }//GEN-LAST:event_num4ActionPerformed

    private void num5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num5ActionPerformed
        int selectedValue = Integer.parseInt(num5.getText());
        if (this.checkValue(selectedValue,round-1)) {
            if (round == 1) {
                this.setPreviousValues();
                String x = num1.getText();
                String y = num5.getText();
                num1.setText(y);
                num5.setText(x);
                this.setVisibleOldValues();
                this.setNumberArray();
                num5.setSelected(false);
                num1.setEnabled(false);
                round += 1;
            } else if(round == 2){
                this.setPreviousValues();
                String x = num2.getText();
                String y = num5.getText();
                num2.setText(y);
                num5.setText(x);
                this.setVisibleOldValues();
                this.setNumberArray();
                num5.setSelected(false);
                num2.setEnabled(false);
                round += 1;
            } else if(round == 3){
                this.setPreviousValues();
                String x = num3.getText();
                String y = num5.getText();
                num3.setText(y);
                num5.setText(x);
                this.setVisibleOldValues();
                this.setNumberArray();
                num5.setSelected(false);
                num3.setEnabled(false);
                round += 1;
            } else if(round == 4){
                this.setPreviousValues();
                String x = num4.getText();
                String y = num5.getText();
                num4.setText(y);
                num5.setText(x);
                this.setVisibleOldValues();
                this.setNumberArray();
                num5.setSelected(false);
                num4.setEnabled(false);
                round += 1;
            } else {                
                JOptionPane.showMessageDialog(this, " You won the game! \n "
                        + " Sorted List \n"
                        + numberArray[0] + " , " + numberArray[1] + " , " 
                        + numberArray[2] + " , " + numberArray[3] + " , "
                        + numberArray[4]);
            }
        }
    }//GEN-LAST:event_num5ActionPerformed

    private boolean checkValue(int selectedValue, int startPosition) {
        int min = numberArray[startPosition];
        for (int i=startPosition; i<5; i++) {
            if (min >= numberArray[i]) {
                min = numberArray[i];
            }
        }
        return (min == selectedValue);
    }

    private void setPreviousValues() {
        sort1.setText(num1.getText());
        sort2.setText(num2.getText());
        sort3.setText(num3.getText());
        sort4.setText(num4.getText());
        sort5.setText(num5.getText());
    }
    
    private void setNumberArray(){
        numberArray[0] = Integer.parseInt(num1.getText());
        numberArray[1] = Integer.parseInt(num2.getText());
        numberArray[2] = Integer.parseInt(num3.getText());
        numberArray[3] = Integer.parseInt(num4.getText());
        numberArray[4] = Integer.parseInt(num5.getText());
    }
    
    private void setVisibleOldValues(){
        sort1.setVisible(true);
        sort2.setVisible(true);
        sort3.setVisible(true);
        sort4.setVisible(true);
        sort5.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectionSortFiveDigit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectionSortFiveDigit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectionSortFiveDigit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectionSortFiveDigit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectionSortFiveDigit(0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton homeBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton num1;
    private javax.swing.JRadioButton num2;
    private javax.swing.JRadioButton num3;
    private javax.swing.JRadioButton num4;
    private javax.swing.JRadioButton num5;
    private javax.swing.JRadioButton sort1;
    private javax.swing.JRadioButton sort2;
    private javax.swing.JRadioButton sort3;
    private javax.swing.JRadioButton sort4;
    private javax.swing.JRadioButton sort5;
    // End of variables declaration//GEN-END:variables
}
