/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sortgame;

import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author ASHI
 */
public class SelectionSort extends javax.swing.JFrame {

    int numberArray[] = new int[5];
    int round = 1;
    int count = 0;

    /**
     * Creates new form SelectionSortFiveDigit
     *
     * @param range
     */
    public SelectionSort() {
        initComponents();

        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        jLabel7.setVisible(false);
        sort1.setVisible(false);
        sort2.setVisible(false);
        sort3.setVisible(false);
        sort4.setVisible(false);
        sort5.setVisible(false);
        sort6.setVisible(false);
        sort7.setVisible(false);
        sort8.setVisible(false);
        sort9.setVisible(false);
        sort10.setVisible(false);
        sort11.setVisible(false);
        sort12.setVisible(false);
        sort13.setVisible(false);
        sort14.setVisible(false);
        sort15.setVisible(false);
        sort16.setVisible(false);
        sort17.setVisible(false);
        sort18.setVisible(false);
        sort19.setVisible(false);
        sort20.setVisible(false);
        sort21.setVisible(false);
        sort22.setVisible(false);
        sort23.setVisible(false);
        sort24.setVisible(false);
        sort25.setVisible(false);

        Random random = new Random();

        int max = 100;
        int min = 1;

        for (int i = 0; i < 5; i++) {
            int randomNumber = random.nextInt(max - min + 1) + min;
            numberArray[i] = randomNumber;
        }

        num1.setText(String.valueOf(numberArray[0]));
        num2.setText(String.valueOf(numberArray[1]));
        num3.setText(String.valueOf(numberArray[2]));
        num4.setText(String.valueOf(numberArray[3]));
        num5.setText(String.valueOf(numberArray[4]));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        homeBtn = new javax.swing.JButton();
        num1 = new javax.swing.JRadioButton();
        num2 = new javax.swing.JRadioButton();
        num3 = new javax.swing.JRadioButton();
        num4 = new javax.swing.JRadioButton();
        num5 = new javax.swing.JRadioButton();
        sort5 = new javax.swing.JRadioButton();
        sort4 = new javax.swing.JRadioButton();
        sort2 = new javax.swing.JRadioButton();
        sort1 = new javax.swing.JRadioButton();
        sort3 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        sort6 = new javax.swing.JRadioButton();
        sort7 = new javax.swing.JRadioButton();
        sort8 = new javax.swing.JRadioButton();
        sort9 = new javax.swing.JRadioButton();
        sort10 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        sort11 = new javax.swing.JRadioButton();
        sort12 = new javax.swing.JRadioButton();
        sort13 = new javax.swing.JRadioButton();
        sort14 = new javax.swing.JRadioButton();
        sort15 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        sort16 = new javax.swing.JRadioButton();
        sort17 = new javax.swing.JRadioButton();
        sort18 = new javax.swing.JRadioButton();
        sort19 = new javax.swing.JRadioButton();
        sort20 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        sort21 = new javax.swing.JRadioButton();
        sort22 = new javax.swing.JRadioButton();
        sort23 = new javax.swing.JRadioButton();
        sort24 = new javax.swing.JRadioButton();
        sort25 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));

        jLabel1.setFont(new java.awt.Font("Trajan Pro", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 255));
        jLabel1.setText("Learn Selection Sort");

        homeBtn.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        homeBtn.setText("Home");
        homeBtn.setActionCommand("");
        homeBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });

        num1.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        num1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        num1.setText("1");
        num1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num1ActionPerformed(evt);
            }
        });

        num2.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        num2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        num2.setText("2");
        num2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num2ActionPerformed(evt);
            }
        });

        num3.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        num3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        num3.setText("3");
        num3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num3ActionPerformed(evt);
            }
        });

        num4.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        num4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        num4.setText("4");
        num4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num4ActionPerformed(evt);
            }
        });

        num5.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        num5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        num5.setText("5");
        num5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num5ActionPerformed(evt);
            }
        });

        sort5.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        sort5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort5.setText("5");
        sort5.setEnabled(false);

        sort4.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        sort4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort4.setText("4");
        sort4.setEnabled(false);

        sort2.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        sort2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort2.setText("2");
        sort2.setEnabled(false);

        sort1.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        sort1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort1.setText("1");
        sort1.setEnabled(false);
        sort1.setHideActionText(true);

        sort3.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        sort3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort3.setText("3");
        sort3.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel2.setText("Select minimum value");

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel3.setText("Round 2");

        jButton1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jButton1.setText("Exit");
        jButton1.setActionCommand("");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        sort6.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        sort6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort6.setText("1");
        sort6.setEnabled(false);

        sort7.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        sort7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort7.setText("2");
        sort7.setEnabled(false);

        sort8.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        sort8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort8.setText("3");
        sort8.setEnabled(false);

        sort9.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        sort9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort9.setText("4");
        sort9.setEnabled(false);

        sort10.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        sort10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort10.setText("5");
        sort10.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel4.setText("Round 1");

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel5.setText("Round 3");

        sort11.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        sort11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort11.setText("1");
        sort11.setEnabled(false);

        sort12.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        sort12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort12.setText("2");
        sort12.setEnabled(false);

        sort13.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        sort13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort13.setText("3");
        sort13.setEnabled(false);

        sort14.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        sort14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort14.setText("4");
        sort14.setEnabled(false);

        sort15.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        sort15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort15.setText("5");
        sort15.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel6.setText("Round 4");

        sort16.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        sort16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort16.setText("1");
        sort16.setEnabled(false);

        sort17.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        sort17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort17.setText("2");
        sort17.setEnabled(false);

        sort18.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        sort18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort18.setText("3");
        sort18.setEnabled(false);

        sort19.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        sort19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort19.setText("4");
        sort19.setEnabled(false);

        sort20.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        sort20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort20.setText("5");
        sort20.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel7.setText("Round 5");

        sort21.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        sort21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort21.setText("1");
        sort21.setEnabled(false);

        sort22.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        sort22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort22.setText("2");
        sort22.setEnabled(false);

        sort23.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        sort23.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort23.setText("3");
        sort23.setEnabled(false);
        sort23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sort23ActionPerformed(evt);
            }
        });

        sort24.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        sort24.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort24.setText("4");
        sort24.setEnabled(false);

        sort25.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        sort25.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort25.setText("5");
        sort25.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 18, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(sort2)
                                        .addComponent(sort7)
                                        .addComponent(sort12)
                                        .addComponent(sort17)
                                        .addComponent(sort22))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(num1)
                                        .addGap(18, 18, 18)
                                        .addComponent(num2)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(sort23)
                                        .addGap(18, 18, 18)
                                        .addComponent(sort24)
                                        .addGap(18, 18, 18)
                                        .addComponent(sort25))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(num3)
                                                .addGap(18, 18, 18)
                                                .addComponent(num4))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(sort3)
                                                .addGap(18, 18, 18)
                                                .addComponent(sort4))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(sort8)
                                                .addGap(18, 18, 18)
                                                .addComponent(sort9))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(sort13)
                                                .addGap(18, 18, 18)
                                                .addComponent(sort14))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(sort18)
                                                .addGap(18, 18, 18)
                                                .addComponent(sort19)))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(sort15)
                                            .addComponent(sort20)
                                            .addComponent(sort10)
                                            .addComponent(sort5)
                                            .addComponent(num5)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(homeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sort6)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(sort11)
                                    .addComponent(sort16)
                                    .addComponent(sort21)
                                    .addComponent(sort1))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num1)
                    .addComponent(num2)
                    .addComponent(num3)
                    .addComponent(num4)
                    .addComponent(num5))
                .addGap(7, 7, 7)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(5, 5, 5)
                        .addComponent(sort6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sort11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sort16)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sort21))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sort2)
                            .addComponent(sort1)
                            .addComponent(sort3)
                            .addComponent(sort4)
                            .addComponent(sort5))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sort7)
                            .addComponent(sort8)
                            .addComponent(sort9)
                            .addComponent(sort10))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sort12)
                            .addComponent(sort13)
                            .addComponent(sort14)
                            .addComponent(sort15))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sort17)
                            .addComponent(sort18)
                            .addComponent(sort19)
                            .addComponent(sort20))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sort22)
                            .addComponent(sort23)
                            .addComponent(sort24)
                            .addComponent(sort25))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(homeBtn)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        SelectionSortHomeScreen selectionSortHomeScreen = new SelectionSortHomeScreen();
        selectionSortHomeScreen.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_homeBtnActionPerformed

    private void num1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num1ActionPerformed
        int selectedValue = Integer.parseInt(num1.getText());
        if (this.checkValue(selectedValue, round - 1)) {
            if (round == 1) {
                this.setPreviousValues();
                this.setVisibleOldValues();
                this.setNumberArray();
                num1.setSelected(false);
                num1.setEnabled(false);
                round += 1;
            }
        } else {
            if (count < 1) {
                JOptionPane.showMessageDialog(this, "Invalid Selection! \n You have only two chances.");
                num1.setSelected(false);
                count += 1;
            } else if (count < 2) {
                JOptionPane.showMessageDialog(this, "Invalid Selection! \n You have only one chance.");
                num1.setSelected(false);
                count += 1;
            } else {
                JOptionPane.showMessageDialog(this, "You lost the game!");
                SelectionSortHomeScreen selectionSortHomeScreen = new SelectionSortHomeScreen();
                selectionSortHomeScreen.setVisible(true);
                this.setVisible(false);
            }
        }
    }//GEN-LAST:event_num1ActionPerformed

    private void num2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num2ActionPerformed
        int selectedValue = Integer.parseInt(num2.getText());
        if (this.checkValue(selectedValue, round - 1)) {
            if (round == 1) {
                this.setPreviousValues();
                String x = num1.getText();
                String y = num2.getText();
                num1.setText(y);
                num2.setText(x);
                this.setVisibleOldValues();
                this.setNumberArray();
                num2.setSelected(false);
                num1.setEnabled(false);
                round += 1;
            } else if (round == 2) {
                this.setPreviousValues();
                this.setVisibleOldValues();
                this.setNumberArray();
                num2.setSelected(false);
                num2.setEnabled(false);
                round += 1;
            }
        } else {
            if (count < 1) {
                JOptionPane.showMessageDialog(this, "Invalid Selection! \n You have only two chances.");
                num2.setSelected(false);
                count += 1;
            } else if (count < 2) {
                JOptionPane.showMessageDialog(this, "Invalid Selection! \n You have only one chance.");
                num2.setSelected(false);
                count += 1;
            } else {
                JOptionPane.showMessageDialog(this, "You lost the game!");
                SelectionSortHomeScreen selectionSortHomeScreen = new SelectionSortHomeScreen();
                selectionSortHomeScreen.setVisible(true);
                this.setVisible(false);
            }
        }
    }//GEN-LAST:event_num2ActionPerformed

    private void num3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num3ActionPerformed
        int selectedValue = Integer.parseInt(num3.getText());
        if (this.checkValue(selectedValue, round - 1)) {
            if (round == 1) {
                this.setPreviousValues();
                String x = num1.getText();
                String y = num3.getText();
                num1.setText(y);
                num3.setText(x);
                this.setVisibleOldValues();
                this.setNumberArray();
                num3.setSelected(false);
                num1.setEnabled(false);
                round += 1;
            } else if (round == 2) {
                this.setPreviousValues();
                String x = num2.getText();
                String y = num3.getText();
                num2.setText(y);
                num3.setText(x);
                this.setVisibleOldValues();
                this.setNumberArray();
                num3.setSelected(false);
                num2.setEnabled(false);
                round += 1;
            } else if (round == 3) {
                this.setPreviousValues();
                this.setVisibleOldValues();
                this.setNumberArray();
                num3.setSelected(false);
                num3.setEnabled(false);
                round += 1;
            }
        } else {
            if (count < 1) {
                JOptionPane.showMessageDialog(this, "Invalid Selection! \n You have only two chances.");
                num3.setSelected(false);
                count += 1;
            } else if (count < 2) {
                JOptionPane.showMessageDialog(this, "Invalid Selection! \n You have only one chance.");
                num3.setSelected(false);
                count += 1;
            } else {
                JOptionPane.showMessageDialog(this, "You lost the game!");
                SelectionSortHomeScreen selectionSortHomeScreen = new SelectionSortHomeScreen();
                selectionSortHomeScreen.setVisible(true);
                this.setVisible(false);
            }
        }
    }//GEN-LAST:event_num3ActionPerformed

    private void num4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num4ActionPerformed
        int selectedValue = Integer.parseInt(num4.getText());
        if (this.checkValue(selectedValue, round - 1)) {
            if (round == 1) {
                this.setPreviousValues();
                String x = num1.getText();
                String y = num4.getText();
                num1.setText(y);
                num4.setText(x);
                this.setVisibleOldValues();
                this.setNumberArray();
                num4.setSelected(false);
                num1.setEnabled(false);
                round += 1;
            } else if (round == 2) {
                this.setPreviousValues();
                String x = num2.getText();
                String y = num4.getText();
                num2.setText(y);
                num4.setText(x);
                this.setVisibleOldValues();
                this.setNumberArray();
                num4.setSelected(false);
                num2.setEnabled(false);
                round += 1;
            } else if (round == 3) {
                this.setPreviousValues();
                String x = num3.getText();
                String y = num4.getText();
                num3.setText(y);
                num4.setText(x);
                this.setVisibleOldValues();
                this.setNumberArray();
                num4.setSelected(false);
                num3.setEnabled(false);
                round += 1;
            } else if (round == 4) {
                this.setPreviousValues();
                this.setVisibleOldValues();
                this.setNumberArray();
                num4.setSelected(false);
                num4.setEnabled(false);
                round += 1;
            }
        } else {
            if (count < 1) {
                JOptionPane.showMessageDialog(this, "Invalid Selection! \n You have only two chances.");
                num4.setSelected(false);
                count += 1;
            } else if (count < 2) {
                JOptionPane.showMessageDialog(this, "Invalid Selection! \n You have only one chance.");
                num4.setSelected(false);
                count += 1;
            } else {
                JOptionPane.showMessageDialog(this, "You lost the game!");
                SelectionSortHomeScreen selectionSortHomeScreen = new SelectionSortHomeScreen();
                selectionSortHomeScreen.setVisible(true);
                this.setVisible(false);
            }
        }
    }//GEN-LAST:event_num4ActionPerformed

    private void num5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num5ActionPerformed
        int selectedValue = Integer.parseInt(num5.getText());
        if (this.checkValue(selectedValue, round - 1)) {
            if (round == 1) {
                this.setPreviousValues();
                String x = num1.getText();
                String y = num5.getText();
                num1.setText(y);
                num5.setText(x);
                this.setVisibleOldValues();
                this.setNumberArray();
                num5.setSelected(false);
                num1.setEnabled(false);
                round += 1;
            } else if (round == 2) {
                this.setPreviousValues();
                String x = num2.getText();
                String y = num5.getText();
                num2.setText(y);
                num5.setText(x);
                this.setVisibleOldValues();
                this.setNumberArray();
                num5.setSelected(false);
                num2.setEnabled(false);
                round += 1;
            } else if (round == 3) {
                this.setPreviousValues();
                String x = num3.getText();
                String y = num5.getText();
                num3.setText(y);
                num5.setText(x);
                this.setVisibleOldValues();
                this.setNumberArray();
                num5.setSelected(false);
                num3.setEnabled(false);
                round += 1;
            } else if (round == 4) {
                this.setPreviousValues();
                String x = num4.getText();
                String y = num5.getText();
                num4.setText(y);
                num5.setText(x);
                this.setVisibleOldValues();
                this.setNumberArray();
                num5.setSelected(false);
                num4.setEnabled(false);
                round += 1;
            } else {
                JOptionPane.showMessageDialog(this, " You won the game! \n "
                        + " Sorted List \n"
                        + numberArray[0] + " , " + numberArray[1] + " , "
                        + numberArray[2] + " , " + numberArray[3] + " , "
                        + numberArray[4]);
                this.setPreviousValues();
                num5.setSelected(false);
                num5.setEnabled(false);
            }
        } else {
            if (count < 1) {
                JOptionPane.showMessageDialog(this, "Invalid Selection! \n You have only two chances.");
                num5.setSelected(false);
                count += 1;
            } else if (count < 2) {
                JOptionPane.showMessageDialog(this, "Invalid Selection! \n You have only one chance.");
                num5.setSelected(false);
                count += 1;
            } else {
                JOptionPane.showMessageDialog(this, "You lost the game!");
                SelectionSortHomeScreen selectionSortHomeScreen = new SelectionSortHomeScreen();
                selectionSortHomeScreen.setVisible(true);
                this.setVisible(false);
            }
        }
    }//GEN-LAST:event_num5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void sort23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sort23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sort23ActionPerformed

    private boolean checkValue(int selectedValue, int startPosition) {
        int min = numberArray[startPosition];
        for (int i = startPosition; i < 5; i++) {
            if (min >= numberArray[i]) {
                min = numberArray[i];
            }
        }
        return (min == selectedValue);
    }

    private void setPreviousValues() {
        sort1.setText(num1.getText());
        sort2.setText(num2.getText());
        sort3.setText(num3.getText());
        sort4.setText(num4.getText());
        sort5.setText(num5.getText());
    }

    private void setNumberArray() {
        numberArray[0] = Integer.parseInt(num1.getText());
        numberArray[1] = Integer.parseInt(num2.getText());
        numberArray[2] = Integer.parseInt(num3.getText());
        numberArray[3] = Integer.parseInt(num4.getText());
        numberArray[4] = Integer.parseInt(num5.getText());
    }

    private void setVisibleOldValues() {
        sort1.setVisible(true);
        sort2.setVisible(true);
        sort3.setVisible(true);
        sort4.setVisible(true);
        sort5.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectionSort.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectionSort.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectionSort.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectionSort.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectionSort().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton homeBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton num1;
    private javax.swing.JRadioButton num2;
    private javax.swing.JRadioButton num3;
    private javax.swing.JRadioButton num4;
    private javax.swing.JRadioButton num5;
    private javax.swing.JRadioButton sort1;
    private javax.swing.JRadioButton sort10;
    private javax.swing.JRadioButton sort11;
    private javax.swing.JRadioButton sort12;
    private javax.swing.JRadioButton sort13;
    private javax.swing.JRadioButton sort14;
    private javax.swing.JRadioButton sort15;
    private javax.swing.JRadioButton sort16;
    private javax.swing.JRadioButton sort17;
    private javax.swing.JRadioButton sort18;
    private javax.swing.JRadioButton sort19;
    private javax.swing.JRadioButton sort2;
    private javax.swing.JRadioButton sort20;
    private javax.swing.JRadioButton sort21;
    private javax.swing.JRadioButton sort22;
    private javax.swing.JRadioButton sort23;
    private javax.swing.JRadioButton sort24;
    private javax.swing.JRadioButton sort25;
    private javax.swing.JRadioButton sort3;
    private javax.swing.JRadioButton sort4;
    private javax.swing.JRadioButton sort5;
    private javax.swing.JRadioButton sort6;
    private javax.swing.JRadioButton sort7;
    private javax.swing.JRadioButton sort8;
    private javax.swing.JRadioButton sort9;
    // End of variables declaration//GEN-END:variables
}
