/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sortgame;

import com.sun.jna.Native;
import com.sun.jna.NativeLibrary;
import java.awt.BorderLayout;
import java.awt.Canvas;
import java.awt.Color;
import java.util.Random;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import static sortgame.SortGame.homeScreen;
import uk.co.caprica.vlcj.binding.LibVlc;
import uk.co.caprica.vlcj.player.MediaPlayerFactory;
import uk.co.caprica.vlcj.player.embedded.EmbeddedMediaPlayer;
import uk.co.caprica.vlcj.runtime.RuntimeUtil;

/**
 *
 * @author ASHI
 */
public class SelectionSort extends javax.swing.JFrame {

    int numberArray[] = new int[5];
    int round = 1;
    int count = 0;

    /**
     * Creates new form SelectionSortFiveDigit
     *
     * @param range
     */
    public SelectionSort() {
        initComponents();

        /* hide the labels and radio buttons */
        round1Lbl.setVisible(false);
        round2Lbl.setVisible(false);
        round3Lbl.setVisible(false);
        round4Lbl.setVisible(false);
        round5Lbl.setVisible(false);
        sort11.setVisible(false);
        sort12.setVisible(false);
        sort13.setVisible(false);
        sort14.setVisible(false);
        sort15.setVisible(false);
        sort21.setVisible(false);
        sort22.setVisible(false);
        sort23.setVisible(false);
        sort24.setVisible(false);
        sort25.setVisible(false);
        sort31.setVisible(false);
        sort32.setVisible(false);
        sort33.setVisible(false);
        sort34.setVisible(false);
        sort35.setVisible(false);
        sort41.setVisible(false);
        sort42.setVisible(false);
        sort43.setVisible(false);
        sort44.setVisible(false);
        sort45.setVisible(false);
        sort51.setVisible(false);
        sort52.setVisible(false);
        sort53.setVisible(false);
        sort54.setVisible(false);
        sort55.setVisible(false);

        Random random = new Random();

        int max = 100;
        int min = 1;

        for (int i = 0; i < 5; i++) {
            int randomNumber = random.nextInt(max - min + 1) + min;
            numberArray[i] = randomNumber;
        }

        num1.setText(String.valueOf(numberArray[0]));
        num2.setText(String.valueOf(numberArray[1]));
        num3.setText(String.valueOf(numberArray[2]));
        num4.setText(String.valueOf(numberArray[3]));
        num5.setText(String.valueOf(numberArray[4]));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        homeBtn = new javax.swing.JButton();
        num1 = new javax.swing.JRadioButton();
        num2 = new javax.swing.JRadioButton();
        num3 = new javax.swing.JRadioButton();
        num4 = new javax.swing.JRadioButton();
        num5 = new javax.swing.JRadioButton();
        sort15 = new javax.swing.JRadioButton();
        sort14 = new javax.swing.JRadioButton();
        sort12 = new javax.swing.JRadioButton();
        sort11 = new javax.swing.JRadioButton();
        sort13 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        exitBtn = new javax.swing.JButton();
        round1Lbl = new javax.swing.JLabel();
        round2Lbl = new javax.swing.JLabel();
        sort21 = new javax.swing.JRadioButton();
        sort22 = new javax.swing.JRadioButton();
        sort23 = new javax.swing.JRadioButton();
        sort24 = new javax.swing.JRadioButton();
        sort25 = new javax.swing.JRadioButton();
        round3Lbl = new javax.swing.JLabel();
        sort31 = new javax.swing.JRadioButton();
        sort32 = new javax.swing.JRadioButton();
        sort33 = new javax.swing.JRadioButton();
        sort34 = new javax.swing.JRadioButton();
        sort35 = new javax.swing.JRadioButton();
        round4Lbl = new javax.swing.JLabel();
        sort41 = new javax.swing.JRadioButton();
        sort42 = new javax.swing.JRadioButton();
        sort43 = new javax.swing.JRadioButton();
        sort44 = new javax.swing.JRadioButton();
        sort45 = new javax.swing.JRadioButton();
        round5Lbl = new javax.swing.JLabel();
        sort51 = new javax.swing.JRadioButton();
        sort52 = new javax.swing.JRadioButton();
        sort53 = new javax.swing.JRadioButton();
        sort54 = new javax.swing.JRadioButton();
        sort55 = new javax.swing.JRadioButton();
        tryAgainBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));

        jLabel1.setFont(new java.awt.Font("Trajan Pro", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 255));
        jLabel1.setText("Learn Selection Sort");

        homeBtn.setBackground(java.awt.SystemColor.window);
        homeBtn.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sortgame/homeIcon.png"))); // NOI18N
        homeBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });

        num1.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        num1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        num1.setText("1");
        num1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num1ActionPerformed(evt);
            }
        });

        num2.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        num2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        num2.setText("2");
        num2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num2ActionPerformed(evt);
            }
        });

        num3.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        num3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        num3.setText("3");
        num3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num3ActionPerformed(evt);
            }
        });

        num4.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        num4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        num4.setText("4");
        num4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num4ActionPerformed(evt);
            }
        });

        num5.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        num5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        num5.setText("5");
        num5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num5ActionPerformed(evt);
            }
        });

        sort15.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        sort15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort15.setText("5");
        sort15.setEnabled(false);

        sort14.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        sort14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort14.setText("4");
        sort14.setEnabled(false);

        sort12.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        sort12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort12.setText("2");
        sort12.setEnabled(false);

        sort11.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        sort11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort11.setText("1");
        sort11.setEnabled(false);
        sort11.setHideActionText(true);
        sort11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sort11ActionPerformed(evt);
            }
        });

        sort13.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        sort13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort13.setText("3");
        sort13.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel2.setText("Select minimum value");

        exitBtn.setBackground(java.awt.SystemColor.window);
        exitBtn.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        exitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sortgame/exitIcon.png"))); // NOI18N
        exitBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        round1Lbl.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        round1Lbl.setText("Round 1");

        round2Lbl.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        round2Lbl.setText("Round 2");

        sort21.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        sort21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort21.setText("1");
        sort21.setEnabled(false);

        sort22.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        sort22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort22.setText("2");
        sort22.setEnabled(false);

        sort23.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        sort23.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort23.setText("3");
        sort23.setEnabled(false);

        sort24.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        sort24.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort24.setText("4");
        sort24.setEnabled(false);

        sort25.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        sort25.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort25.setText("5");
        sort25.setEnabled(false);

        round3Lbl.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        round3Lbl.setText("Round 3");

        sort31.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        sort31.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort31.setText("1");
        sort31.setEnabled(false);

        sort32.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        sort32.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort32.setText("2");
        sort32.setEnabled(false);

        sort33.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        sort33.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort33.setText("3");
        sort33.setEnabled(false);

        sort34.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        sort34.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort34.setText("4");
        sort34.setEnabled(false);

        sort35.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        sort35.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort35.setText("5");
        sort35.setEnabled(false);

        round4Lbl.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        round4Lbl.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        round4Lbl.setText("Round 4");

        sort41.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        sort41.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort41.setText("1");
        sort41.setEnabled(false);

        sort42.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        sort42.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort42.setText("2");
        sort42.setEnabled(false);

        sort43.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        sort43.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort43.setText("3");
        sort43.setEnabled(false);

        sort44.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        sort44.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort44.setText("4");
        sort44.setEnabled(false);

        sort45.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        sort45.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort45.setText("5");
        sort45.setEnabled(false);

        round5Lbl.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        round5Lbl.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        round5Lbl.setText("Round 5");

        sort51.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        sort51.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort51.setText("1");
        sort51.setEnabled(false);

        sort52.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        sort52.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort52.setText("2");
        sort52.setEnabled(false);

        sort53.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        sort53.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort53.setText("3");
        sort53.setEnabled(false);

        sort54.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        sort54.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort54.setText("4");
        sort54.setEnabled(false);

        sort55.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        sort55.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sort55.setText("5");
        sort55.setEnabled(false);

        tryAgainBtn.setBackground(java.awt.SystemColor.window);
        tryAgainBtn.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        tryAgainBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sortgame/reload.png"))); // NOI18N
        tryAgainBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tryAgainBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tryAgainBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(sort11)
                                .addGap(18, 18, 18)
                                .addComponent(sort12))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(num1)
                                .addGap(18, 18, 18)
                                .addComponent(num2)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(num3)
                                .addGap(18, 18, 18)
                                .addComponent(num4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(sort13)
                                .addGap(18, 18, 18)
                                .addComponent(sort14)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sort15)
                            .addComponent(num5)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(round1Lbl)
                            .addComponent(round2Lbl)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(round3Lbl)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(sort21)
                                        .addGap(18, 18, 18)
                                        .addComponent(sort22)
                                        .addGap(18, 18, 18)
                                        .addComponent(sort23)
                                        .addGap(18, 18, 18)
                                        .addComponent(sort24)))
                                .addGap(18, 18, 18)
                                .addComponent(sort25))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(round4Lbl)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(sort31)
                                        .addGap(18, 18, 18)
                                        .addComponent(sort32)
                                        .addGap(18, 18, 18)
                                        .addComponent(sort33)
                                        .addGap(18, 18, 18)
                                        .addComponent(sort34)))
                                .addGap(18, 18, 18)
                                .addComponent(sort35))
                            .addComponent(round5Lbl)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(sort41)
                                        .addGap(18, 18, 18)
                                        .addComponent(sort42))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(sort51)
                                        .addGap(18, 18, 18)
                                        .addComponent(sort52)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sort43)
                                    .addComponent(sort53))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sort44)
                                    .addComponent(sort54))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sort55)
                                    .addComponent(sort45))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tryAgainBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(homeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num1)
                    .addComponent(num2)
                    .addComponent(num3)
                    .addComponent(num4)
                    .addComponent(num5))
                .addGap(7, 7, 7)
                .addComponent(round1Lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sort12)
                    .addComponent(sort11)
                    .addComponent(sort13)
                    .addComponent(sort14)
                    .addComponent(sort15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(round2Lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sort21)
                    .addComponent(sort22)
                    .addComponent(sort23)
                    .addComponent(sort24)
                    .addComponent(sort25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(round3Lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sort31)
                    .addComponent(sort32)
                    .addComponent(sort33)
                    .addComponent(sort34)
                    .addComponent(sort35))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(round4Lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sort41)
                    .addComponent(sort42)
                    .addComponent(sort43)
                    .addComponent(sort44)
                    .addComponent(sort45))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(round5Lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sort51)
                    .addComponent(sort52)
                    .addComponent(sort53)
                    .addComponent(sort54)
                    .addComponent(sort55))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(homeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tryAgainBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitBtnActionPerformed

    private void sort11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sort11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sort11ActionPerformed

    private void num5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num5ActionPerformed
        int selectedValue = Integer.parseInt(num5.getText());
        if (this.checkValue(selectedValue, round - 1)) {

            if (round == 1) {
                this.setRoundOne(num5, sort15);
            } else if (round == 2) {
                this.setRoundTwo(num5, sort25);
            } else if (round == 3) {
                this.setRoundThree(num5, sort35);
            } else if (round == 4) {
                this.setRoundFour(num5, sort45);
            } else {
                this.setRoundFive(num5, sort55);
                JOptionPane.showMessageDialog(this, " You won the game! ");
            }

        } else {
            if (count < 1) {
                this.countOneError(num5);

            } else if (count < 2) {
                this.countTwoError(num5);

            } else {
                this.finalError();
            }
        }
    }//GEN-LAST:event_num5ActionPerformed

    private void num4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num4ActionPerformed
        int selectedValue = Integer.parseInt(num4.getText());
        if (this.checkValue(selectedValue, round - 1)) {

            if (round == 1) {
                this.setRoundOne(num4, sort14);
            } else if (round == 2) {
                this.setRoundTwo(num4, sort24);
            } else if (round == 3) {
                this.setRoundThree(num4, sort34);
            } else if (round == 4) {
                this.setRoundFour(num4, sort44);
            }

        } else {
            if (count < 1) {
                this.countOneError(num4);

            } else if (count < 2) {
                this.countTwoError(num4);

            } else {
                this.finalError();
            }
        }
    }//GEN-LAST:event_num4ActionPerformed

    private void num3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num3ActionPerformed
        int selectedValue = Integer.parseInt(num3.getText());
        if (this.checkValue(selectedValue, round - 1)) {

            if (round == 1) {
                this.setRoundOne(num3, sort13);
            } else if (round == 2) {
                this.setRoundTwo(num3, sort23);
            } else if (round == 3) {
                this.setRoundThree(num3, sort33);
            }

        } else {
            if (count < 1) {
                this.countOneError(num3);

            } else if (count < 2) {
                this.countTwoError(num3);

            } else {
                this.finalError();
            }
        }
    }//GEN-LAST:event_num3ActionPerformed

    private void num2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num2ActionPerformed
        int selectedValue = Integer.parseInt(num2.getText());

        if (this.checkValue(selectedValue, round - 1)) {

            if (round == 1) {
                this.setRoundOne(num2, sort12);
            } else if (round == 2) {
                this.setRoundTwo(num2, sort22);
            }

        } else {
            if (count < 1) {
                this.countOneError(num2);

            } else if (count < 2) {
                this.countTwoError(num2);

            } else {
                this.finalError();
            }
        }
    }//GEN-LAST:event_num2ActionPerformed

    private void num1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num1ActionPerformed

        int selectedValue = Integer.parseInt(num1.getText());

        if (this.checkValue(selectedValue, round - 1)) {
            if (round == 1) {
                this.setRoundOne(num1, sort11);
            }

        } else {
            if (count < 1) {
                this.countOneError(num1);

            } else if (count < 2) {
                this.countTwoError(num1);

            } else {
                this.finalError();
            }
        }
    }//GEN-LAST:event_num1ActionPerformed

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        HomeScreen homeScreen = new HomeScreen();
        homeScreen.setLocation(400, 100);
        homeScreen.setSize(500, 300);
        homeScreen.setResizable(false);
        homeScreen.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeBtnActionPerformed

    private void tryAgainBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tryAgainBtnActionPerformed
        SelectionSort selectionSort = new SelectionSort();
        selectionSort.setLocation(550, 10);
        selectionSort.setResizable(false);
        selectionSort.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tryAgainBtnActionPerformed

    /* Start of method checkValue to check selected value is current minimum or not */
    private boolean checkValue(int selectedValue, int startPosition) {
        int min = numberArray[startPosition];
        for (int i = startPosition; i < 5; i++) {
            if (min >= numberArray[i]) {
                min = numberArray[i];
            }
        }
        return (min == selectedValue);
    }
    /* End of method checkValue */

    /* Start of method setPreviousValues to catch previous rounds */
    private void setPreviousValues(JRadioButton sortNum1, JRadioButton sortNum2, JRadioButton sortNum3, JRadioButton sortNum4, JRadioButton sortNum5) {
        sortNum1.setText(num1.getText());
        sortNum2.setText(num2.getText());
        sortNum3.setText(num3.getText());
        sortNum4.setText(num4.getText());
        sortNum5.setText(num5.getText());
    }
    /* End of method setPreviousValues */

    /* Start of setNumberArray method */
    private void setNumberArray() {
        numberArray[0] = Integer.parseInt(num1.getText());
        numberArray[1] = Integer.parseInt(num2.getText());
        numberArray[2] = Integer.parseInt(num3.getText());
        numberArray[3] = Integer.parseInt(num4.getText());
        numberArray[4] = Integer.parseInt(num5.getText());
    }
    /* End of setNumberArray method */

    /* Start of method setVisibleOldValues to visible the round */
    private void setVisibleOldValues(JRadioButton sortNum1, JRadioButton sortNum2, JRadioButton sortNum3, JRadioButton sortNum4, JRadioButton sortNum5) {
        sortNum1.setVisible(true);
        sortNum2.setVisible(true);
        sortNum3.setVisible(true);
        sortNum4.setVisible(true);
        sortNum5.setVisible(true);
    }
    /* End of method setVisibleOldValuess */

    /* Start of setRoundOne method */
    private void setRoundOne(JRadioButton selectedNum, JRadioButton sortNum) {

        //set round 1 values
        round1Lbl.setVisible(true);
        this.setPreviousValues(sort11, sort12, sort13, sort14, sort15);
        this.setVisibleOldValues(sort11, sort12, sort13, sort14, sort15);

        String x = num1.getText();
        String y = selectedNum.getText();
        num1.setText(y);
        selectedNum.setText(x);

        //highlight swap numbers
        sort11.setBackground(Color.CYAN);
        sortNum.setBackground(Color.GREEN);

        this.setNumberArray();

        selectedNum.setSelected(false);
        num1.setEnabled(false);

        round += 1;
    }
    /* End of setRoundOne method */

    /* Start of setRoundTwo method */
    private void setRoundTwo(JRadioButton selectedNum, JRadioButton sortNum) {

        //set round 1 values
        round2Lbl.setVisible(true);
        this.setPreviousValues(sort21, sort22, sort23, sort24, sort25);
        this.setVisibleOldValues(sort21, sort22, sort23, sort24, sort25);

        String x = num2.getText();
        String y = selectedNum.getText();
        num2.setText(y);
        selectedNum.setText(x);

        //highlight swap numbers
        sort22.setBackground(Color.CYAN);
        sortNum.setBackground(Color.GREEN);

        this.setNumberArray();

        selectedNum.setSelected(false);
        num2.setEnabled(false);

        round += 1;
    }
    /* End of setRoundTwo method */

    /* Start of setRoundThree method */
    private void setRoundThree(JRadioButton selectedNum, JRadioButton sortNum) {

        //set round 1 values
        round3Lbl.setVisible(true);
        this.setPreviousValues(sort31, sort32, sort33, sort34, sort35);
        this.setVisibleOldValues(sort31, sort32, sort33, sort34, sort35);

        String x = num3.getText();
        String y = selectedNum.getText();
        num3.setText(y);
        selectedNum.setText(x);

        //highlight swap numbers
        sort33.setBackground(Color.CYAN);
        sortNum.setBackground(Color.GREEN);

        this.setNumberArray();

        selectedNum.setSelected(false);
        num3.setEnabled(false);

        round += 1;
    }
    /* End of setRoundThree method */

    /* Start of setRoundFour method */
    private void setRoundFour(JRadioButton selectedNum, JRadioButton sortNum) {

        //set round 1 values
        round4Lbl.setVisible(true);
        this.setPreviousValues(sort41, sort42, sort43, sort44, sort45);
        this.setVisibleOldValues(sort41, sort42, sort43, sort44, sort45);

        String x = num4.getText();
        String y = selectedNum.getText();
        num4.setText(y);
        selectedNum.setText(x);

        //highlight swap numbers
        sort44.setBackground(Color.CYAN);
        sortNum.setBackground(Color.GREEN);

        this.setNumberArray();

        selectedNum.setSelected(false);
        num4.setEnabled(false);

        round += 1;
    }
    /* End of setRoundFour method */

    /* Start of setRoundFive method */
    private void setRoundFive(JRadioButton selectedNum, JRadioButton sortNum) {

        //set round 1 values
        round5Lbl.setVisible(true);
        this.setPreviousValues(sort51, sort52, sort53, sort54, sort55);
        this.setVisibleOldValues(sort51, sort52, sort53, sort54, sort55);

        String x = num5.getText();
        String y = selectedNum.getText();
        num5.setText(y);
        selectedNum.setText(x);

        //highlight swap numbers
        sort55.setBackground(Color.CYAN);
        sortNum.setBackground(Color.GREEN);

        this.setNumberArray();

        selectedNum.setSelected(false);
        num5.setEnabled(false);

        round += 1;
    }
    /* End of setRoundFive method */

    /* Start of countOneError method */
    private void countOneError(JRadioButton selectedNum) {
        JOptionPane.showMessageDialog(this, "Invalid Selection! \n You have only two chances.");
        selectedNum.setSelected(false);
        count += 1;
    }
    /* End of countOneError method */

    /* Start of countTwoError method */
    private void countTwoError(JRadioButton selectedNum) {
        JOptionPane.showMessageDialog(this, "Invalid Selection! \n You have only one chance.");
        selectedNum.setSelected(false);
        count += 1;
    }
    /* End of countTwoError method */

    /* Start of finalError method */
    private void finalError() {
        JOptionPane.showMessageDialog(this, "You lost the game! Please follow video again & then try this ! ");
        SelectionSortVideo selectionSortVideo = new SelectionSortVideo();
        selectionSortVideo.setLocation(400, 100);
        selectionSortVideo.setSize(600, 400);
        selectionSortVideo.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        selectionSortVideo.setResizable(false);
        selectionSortVideo.setVisible(true);

        Canvas canvas = new Canvas();

        canvas.setBackground(Color.black);

        try {
            selectionSortVideo.videoPanel.setLayout(new BorderLayout());

            selectionSortVideo.videoPanel.add(canvas);
            selectionSortVideo.add(selectionSortVideo.videoPanel);

            NativeLibrary.addSearchPath(RuntimeUtil.getLibVlcLibraryName(), "lib");
            Native.loadLibrary(RuntimeUtil.getLibVlcLibraryName(), LibVlc.class);

            MediaPlayerFactory mpf = new MediaPlayerFactory();

            EmbeddedMediaPlayer emp = mpf.newEmbeddedMediaPlayer();
            emp.setVideoSurface(mpf.newVideoSurface(canvas));

            emp.toggleFullScreen();

            emp.setEnableKeyInputHandling(false);
            emp.setEnableMouseInputHandling(false);

            String file = "Selection Sort Intro.mp4";

            emp.prepareMedia(file);

            emp.play();

        } catch (Exception e) {
            System.err.println("Exception : " + e);
        }

        this.dispose();
    }
    /* End of finalError method */

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectionSort.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectionSort.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectionSort.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectionSort.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectionSort().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitBtn;
    private javax.swing.JButton homeBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton num1;
    private javax.swing.JRadioButton num2;
    private javax.swing.JRadioButton num3;
    private javax.swing.JRadioButton num4;
    private javax.swing.JRadioButton num5;
    private javax.swing.JLabel round1Lbl;
    private javax.swing.JLabel round2Lbl;
    private javax.swing.JLabel round3Lbl;
    private javax.swing.JLabel round4Lbl;
    private javax.swing.JLabel round5Lbl;
    private javax.swing.JRadioButton sort11;
    private javax.swing.JRadioButton sort12;
    private javax.swing.JRadioButton sort13;
    private javax.swing.JRadioButton sort14;
    private javax.swing.JRadioButton sort15;
    private javax.swing.JRadioButton sort21;
    private javax.swing.JRadioButton sort22;
    private javax.swing.JRadioButton sort23;
    private javax.swing.JRadioButton sort24;
    private javax.swing.JRadioButton sort25;
    private javax.swing.JRadioButton sort31;
    private javax.swing.JRadioButton sort32;
    private javax.swing.JRadioButton sort33;
    private javax.swing.JRadioButton sort34;
    private javax.swing.JRadioButton sort35;
    private javax.swing.JRadioButton sort41;
    private javax.swing.JRadioButton sort42;
    private javax.swing.JRadioButton sort43;
    private javax.swing.JRadioButton sort44;
    private javax.swing.JRadioButton sort45;
    private javax.swing.JRadioButton sort51;
    private javax.swing.JRadioButton sort52;
    private javax.swing.JRadioButton sort53;
    private javax.swing.JRadioButton sort54;
    private javax.swing.JRadioButton sort55;
    private javax.swing.JButton tryAgainBtn;
    // End of variables declaration//GEN-END:variables
}
